### PR TITLE
add support for tags

### PR DESCRIPTION
**Pull request by wagle**
remove some trailing whitespace
add newline at end of defaults.js

### CODE REVIEW

**Comment by wagle** [comment]
mostly my tag support
deleted some trailing whitespace in both your and my stuff
my editor added a newline at the end of defaults.js

**Comment by wagle** [comment]
Any news on including some variant of this patch?

**Comment by kashiif** [comment]
I tried to get it working but it breaks one thing or another. Can't remember exactly but it it did not work as expected even when I tried to fix it

**Comment by wagle** [comment]
I can fix it if I knew what was wrong (Works For Me [tm]).

**Comment by kashiif** [comment]
Can't really recall from the top of my head. If you can remove the merge conflict, I can give it a try again and let you know the issues.

**Comment by wagle** [comment]
Only "problem" Isee right now with that is the unterminated line at the end of  src/chrome/content/editbookmarkplus.js ?

**Comment by wagle** [comment]
Oh..  I think my git decided to trim trailing whitespace.

**Comment by wagle** [comment]
No, git complained and I ran dos2unix on everything..  You want to do that as a separate commt, or shall I, or should I remove it?

**Comment by wagle** [comment]
See new pull request.

**Pull request closed without merging**
